VacationFormPractice/Controllers/TravelerProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VacationFormPractice.Data;
using VacationFormPractice.Models;

namespace VacationFormPractice.Controllers
{
    public class TravelerProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TravelerProfilesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TravelerProfiles
        public async Task<IActionResult> Index()
        {           
            return View(await _context.travelerProfiles.ToListAsync()); //NOTE: Where did we get travelerProfiles from? This came from the ApplicationDbContext that was generated as the name for the dbSet. It is also the name of the table
        }

        //FORM CONFIRMATION: CONFIRM IF INFORMATION ON FORM IS CORRECT.

        List<TravelerProfile> NewProfile = new List<TravelerProfile>();

        public IActionResult FormConfirmation(string fname, string lname, string destination, decimal Budget, string Email, int phone)        
        {
            NewProfile.Add(new TravelerProfile
            {
                FirstName = fname,
                LastName = lname,
                DreamDestination = destination,
                budget = Budget,
                email = Email,
                phoneNumber = phone
            });

            return View(NewProfile);
        }

        // GET: TravelerProfiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelerProfile = await _context.travelerProfiles
                .SingleOrDefaultAsync(m => m.id == id);
            if (travelerProfile == null)
            {
                return NotFound();
            }

            return View(travelerProfile);
        }

        private TravelerProfile db = new TravelerProfile();

        // GET: TravelerProfiles/Create
        
        public IActionResult Create() //NOTE: CREATE the form for the traveler.
        {
            //_context.SaveChanges();
            return View();
        }

        // POST: TravelerProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //NOTE: The bottom method (Create) returns to us the LIST of ALL the travelers generated from the above list.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,FirstName,LastName,DreamDestination,email,phoneNumber,budget")] TravelerProfile travelerProfile) //NOTE: To ADD A COLUMN: Update the bind.
        {
            if (ModelState.IsValid)
            {
                _context.Add(travelerProfile); // <= Add new value to table. NOTE:
                await _context.SaveChangesAsync(); // <= Save Changes. NOTE: 
                return RedirectToAction(nameof(Index));
            }
            return View(travelerProfile);
        }

        // GET: TravelerProfiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return Content("Please enter the id number of the person you want to edit in the URL search bar.");
            }

            var travelerProfile = await _context.travelerProfiles.SingleOrDefaultAsync(m => m.id == id);

            if (travelerProfile == null)
            {
                return Content("ID number is not found.");
            }
            return View(travelerProfile);
        }

        // POST: TravelerProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,FirstName,LastName,DreamDestination,budget")] TravelerProfile travelerProfile)
        {
            if (id != travelerProfile.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(travelerProfile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelerProfileExists(travelerProfile.id))
                    {
                        return NotFound();
                    }
                    else
                    {                        
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(travelerProfile);
        }

        // GET: TravelerProfiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelerProfile = await _context.travelerProfiles
                .SingleOrDefaultAsync(m => m.id == id);
            if (travelerProfile == null)
            {
                return NotFound();
            }

            return View(travelerProfile);
        }

        // POST: TravelerProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var travelerProfile = await _context.travelerProfiles.SingleOrDefaultAsync(m => m.id == id);
            _context.travelerProfiles.Remove(travelerProfile);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelerProfileExists(int id)
        {
            return _context.travelerProfiles.Any(e => e.id == id);
        }
    }
}

VacationFormPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vacation Form Practice</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <style type="text/css">
        body {
            background-image: url("../../wwwroot/images/HongKong.jpg");
            background-position: center;            
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="border: 1px solid black; background-color: lavender">
        <div class="container">
            <div class="navbar-header">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><h1 style="text-align: center">Vacation Form Practice</h1></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav collapse">                    
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="TravelerProfiles" asp-action="Create">Get Started On Your DREAM VACATION Now!!!</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()       
        
    </div>
    <!--
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
        -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>